11.16. Надо подкачаться
htmlacademy-javascript/2102773-keksobooking-27 pull request #10
Opened 2022-11-08 10:50 UTC by gerbertwest

2022-11-08 13:15 UTC, babtshe requested changes
Можно отправить невалидную форму:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/30229773/200574219-1e4f0ce3-16b4-4019-b039-d951d8e2ff07.png">

2022-11-08 13:15 UTC, babtshe commented on js/api.js
> +  fetch('https://27.javascript.pages.academy/keksobooking/data')
хорошо бы в константу вынести.

2022-11-08 13:15 UTC, babtshe commented on js/main.js
> +});
есть смысл переименовать функции с `on` во что-то наподобие `enable/disable` `activate/deactivate` иначе их легко спутать со всякими обработчиками вроде `onClick`

  Кроме этого, было бы полезно переименовать их так, чтобы было понятно что именно они включают/выключают

2022-11-08 13:35 UTC, gerbertwest commented on js/api.js
> +  fetch('https://27.javascript.pages.academy/keksobooking/data')
В смысле саму ссылку на сервер вынести в константу, а в fetch на нее сослаться?

2022-11-10 07:13 UTC, babtshe approved these changes

2022-11-10 07:13 UTC, merged