Генерация разметки объявлений на основе данных
htmlacademy-javascript/2102773-keksobooking-27 pull request #5
Opened 2022-10-20 18:44 UTC by gerbertwest

2022-10-21 15:47 UTC, babtshe requested changes

2022-10-21 15:47 UTC, babtshe commented on js/data.js
> +  MAX_LALITUDE: 35.70000,
❗️

2022-10-21 15:47 UTC, babtshe commented on js/data.js
> +  MAX_PRISE: 10000
у❗️

2022-10-21 15:47 UTC, babtshe commented on js/data.js
> +const location = {
см [критерий](https://up.htmlacademy.ru/javascript/27/criteries#b3) по форматированию перечислений

2022-10-21 15:47 UTC, babtshe commented on js/data.js
>  const createLocation = () => ({
В каких-то случаях функция, которая возвращает значение, содержит в названии get, а где-то create. Хорошо бы добавить единообразия и привести названия к одному виду.

2022-10-21 15:47 UTC, babtshe commented on js/popup.js
> +const mapsCanvas = getArrayOfNoticeObjects();
Хорошо бы поменять названия переменных так, чтобы было понятно что внутри. Например, если в переменной хранится ссылка на элемент, можно добавить в название element или node.

2022-10-21 15:47 UTC, babtshe commented on js/popup.js
> +  const mapElement = cardTemplate.cloneNode(true);
для улучшения читаемости будет полезно разложить параметры по отдельным переменным уже внутри тела функции.

Кроме того, хорошо бы разделить эту огромную функцию на несколько небольших.

2022-10-21 15:47 UTC, babtshe commented on js/popup.js
> +  const featuresConteiner = mapElement.querySelector('.popup__features');
❗️

2022-10-22 17:43 UTC, babtshe requested changes

2022-10-22 17:43 UTC, babtshe commented on js/data.js
> +  MAX_LALITUDE: 35.70000,
опечатку так и не исправил

2022-10-22 17:43 UTC, babtshe commented on js/data.js
> +  MAX_PRISE: 10000
опечатку не исправил, + [критерий](https://up.htmlacademy.ru/javascript/27/criteries#d3) и дальше по коду

2022-10-22 17:43 UTC, babtshe commented on js/popup.js
> +const getPhoto = (mapElement, photos) => {
если в названии функции есть get, она должна что-то возвращать, а если возврат не предполагается, то хорошо бы переименовать. И дальше по коду тоже встречается.

2022-10-22 18:23 UTC, gerbertwest commented on js/data.js
> +  MAX_LALITUDE: 35.70000,
Прошу прощения, я правильно понимаю, что речь о том, что названия объектом должны быть с большой буквы: Location, Rooms, Price, Guests? Я в последнем коммите так и сделал, по критерию Б8

2022-10-22 18:24 UTC, gerbertwest commented on js/data.js
> +  MAX_PRISE: 10000
по этому критерию нужно оставить только MIN и MAX, убрать название объекта?

2022-10-22 18:29 UTC, gerbertwest commented on js/popup.js
> +const getPhoto = (mapElement, photos) => {
Подскажите, как переименовать? Формальности именованию сложно даются

2022-10-23 07:43 UTC, babtshe commented on js/data.js
> +  MAX_LALITUDE: 35.70000,
да, плюс опечатки в названиях параметра стоит поправить

2022-10-23 07:43 UTC, babtshe commented on js/data.js
> +  MAX_PRISE: 10000
именно

2022-10-23 07:44 UTC, babtshe commented on js/popup.js
> +const getPhoto = (mapElement, photos) => {
Из названия должно быть понятно что функция делает, без необходимости заглядывать в код.

2022-10-24 07:07 UTC, babtshe approved these changes

2022-10-24 07:07 UTC, merged