Правда или действие (часть 1)
htmlacademy-javascript/2102773-keksobooking-27 pull request #6
Opened 2022-10-25 20:03 UTC by gerbertwest

2022-10-26 10:30 UTC, babtshe requested changes

2022-10-26 10:30 UTC, babtshe commented on index.html
> +          <input id="title" name="title" type="text"
Было бы полезно здесь и далее разметить максимальные и минимальные значения с помощью атрибутов, см [ТЗ](https://up.htmlacademy.ru/javascript/27/project/keksobooking#keksobooking-3)

2022-10-26 10:30 UTC, babtshe commented on js/notice-form.js
> +};
Хардкодить поля с количеством комнат - ненадёжно. Что если в будущем количество будет меняться? Заполнять массив для десятка гостей может быть уже долго. Будет здорово найти закономерность и научить код работать с любым количеством гостей/комнат до 100.

2022-10-26 10:30 UTC, babtshe commented on js/popup.js
> +    mapElement.querySelector('.popup__text--capacity').textContent = `${rooms } комнаты для ${ guests } гостей`;
здесь хорошо будет менять окончания слов в зависимости от числа.

2022-10-26 18:16 UTC, gerbertwest commented on js/notice-form.js
> +};
К сожалению, нет идей, как это реализовать. Понятно, что кол-во гостей это массив от 1 до I=кол-ву комнат. за исключением 100. но не понимаю, как реализовать это в коде.

2022-10-28 11:00 UTC, babtshe approved these changes

2022-10-28 11:00 UTC, merged